import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import './globals.css'
import Footer from '@/components/footer'
import Navbar from '@/components/navbar'
import ReactQueryProvider from '@/providers/react-query-provider'

const font = Urbanist({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: {
		default: 'Nextjs-ecommerce',
		template: '%s | Nextjs-ecommerce',
	},
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={font.className}>
				<ReactQueryProvider>
					<div className='min-h-screen flex flex-col'>
						<Navbar />
						<main className='flex-grow'>{children}</main>
						<Footer />
					</div>
				</ReactQueryProvider>
			</body>
		</html>
	)
}
