import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import './globals.css'
import Footer from '@/components/footer'
import Navbar from '@/components/navbar'

const font = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: {
		default: 'Nextjs-ecommerce',
		template: '%s | Nextjs-ecommerce',
	},
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={font.className}>
				<div className='min-h-screen flex flex-col'>
					<Navbar />
					<main className='flex-grow'>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
